FROM rust:latest AS worker-builder

COPY . .

RUN cargo build -p tig-worker --release


FROM python:latest

WORKDIR /app

COPY --from=worker-builder /target/release/tig-worker /app/tig-worker

COPY ./tig-benchmarker .

RUN pip install -r requirements.slave.txt

CMD ["python", "slave.py"]