use super::TrackConfig;
pub fn config() -> TrackConfig {
    TrackConfig {
        refinement: 3000,
        ils: 30,
        ils_refine: 100,
        polish: 200,
        post_balance: 80,
        move_limit: 200_000,
        extra_window: 49_152,
        tabu_tenure: 12,
        use_gpu_swaps: true,
        num_init_restarts: 5,
        scout_rounds: 0,
        vcycle_depth: 0,
        vcycle_ils_freq: 0,
        vcycle_post_refine: 0,
        neg_gain_thresh: 5,
        swap_scan_limit: 64,
        cycle_scan_limit: 20,
        cpu_fm_rounds: 6,
        cpu_fm_max_degree: 512,
        ils_cpu_fm: 2,
        final_swap_rounds: 10,
        final_cycle_limit: 20,
        max_coarsen_levels: 7,
        min_coarse_nodes: 400,
        perturb_strong: 2,
        perturb_stagnant_thresh: 3,
        perturb_stagnant_strength: 1,
        balance_weight: 4,
        stagnation_limit: 8,
        use_tiebreaker: true,
    }
}
