use super::TrackConfig;
pub fn config() -> TrackConfig {
    TrackConfig {
        refinement: 4000,
        ils: 30,
        ils_refine: 80,
        polish: 200,
        post_balance: 80,
        move_limit: 200_000,
        extra_window: 57_344,
        tabu_tenure: 12,
        use_gpu_swaps: true,
        num_init_restarts: 5,
        scout_rounds: 0,
        vcycle_depth: 0,
        vcycle_ils_freq: 0,
        vcycle_post_refine: 0,
        neg_gain_thresh: 5,
        swap_scan_limit: 64,
        cycle_scan_limit: 16,
        cpu_fm_rounds: 3,
        cpu_fm_max_degree: 256,
        ils_cpu_fm: 0,
        final_swap_rounds: 10,
        final_cycle_limit: 16,
        max_coarsen_levels: 5,
        min_coarse_nodes: 800,
        perturb_strong: 2,
        perturb_stagnant_thresh: 4,
        perturb_stagnant_strength: 2,
        balance_weight: 4,
        stagnation_limit: 20,
        use_tiebreaker: false,
    }
}
