use super::TrackConfig;
pub fn config() -> TrackConfig {
    TrackConfig {
        refinement: 5000,
        ils: 50,
        ils_refine: 80,
        polish: 300,
        post_balance: 100,
        move_limit: 200_000,
        extra_window: 61_440,
        tabu_tenure: 12,
        use_gpu_swaps: true,
        num_init_restarts: 6,
        scout_rounds: 30,
        vcycle_depth: 0,
        vcycle_ils_freq: 0,
        vcycle_post_refine: 0,
        neg_gain_thresh: 5,
        swap_scan_limit: 64,
        cycle_scan_limit: 16,
        cpu_fm_rounds: 4,
        cpu_fm_max_degree: 128,
        ils_cpu_fm: 0,
        final_swap_rounds: 10,
        final_cycle_limit: 16,
        max_coarsen_levels: 4,
        min_coarse_nodes: 2000,
        perturb_strong: 3,
        perturb_stagnant_thresh: 3,
        perturb_stagnant_strength: 3,
        balance_weight: 2,
        stagnation_limit: 20,
        use_tiebreaker: false,
    }
}
