use super::TrackConfig;
pub fn config() -> TrackConfig {
    TrackConfig {
        refinement: 8000,
        ils: 150,
        ils_refine: 120,
        polish: 600,
        post_balance: 120,
        move_limit: 200_000,
        extra_window: 16_384,
        tabu_tenure: 10,
        use_gpu_swaps: true,
        num_init_restarts: 8,
        scout_rounds: 60,
        vcycle_depth: 0,
        vcycle_ils_freq: 0,
        vcycle_post_refine: 0,
        neg_gain_thresh: 5,
        swap_scan_limit: 96,
        cycle_scan_limit: 32,
        cpu_fm_rounds: 12,
        cpu_fm_max_degree: 512,
        ils_cpu_fm: 3,
        final_swap_rounds: 18,
        final_cycle_limit: 32,
        max_coarsen_levels: 6,
        min_coarse_nodes: 500,
        perturb_strong: 2,
        perturb_stagnant_thresh: 5,
        perturb_stagnant_strength: 1,
        balance_weight: 4,
        stagnation_limit: 20,
        use_tiebreaker: true,
    }
}
