#!/bin/bash

set -e

# Check if CHALLENGE and ALGORITHM arguments are provided
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Error: CHALLENGE and ALGORITHM arguments are required."
  echo "Usage: $0 <CHALLENGE> <ALGORITHM>"
  exit 1
fi

CHALLENGE="$1"
ALGORITHM="$2"

echo "Building ALGORITHM '$ALGORITHM' for CHALLENGE '$CHALLENGE'"
build_so $CHALLENGE $ALGORITHM