services:
  db:
    image: bitnami/postgresql:latest
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - ./db_data:/bitnami/postgresql
    networks:
      - tig-benchmarker
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - tig-benchmarker
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    container_name: master
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - tig-benchmarker
    ports:
      - 5115:5115
      - 3336:3336
    depends_on:
      - db

  ui:
    container_name: ui
    build: 
      context: ./ui
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - tig-benchmarker
    ports:
      - 8083:80
    depends_on:
      - master

networks:
  tig-benchmarker:

volumes:
  pgadmin-data: