use serde_json::{Number, Value};

pub fn n(v: u64) -> Value { Value::Number(Number::from(v)) }
pub fn f(v: f64) -> Value { Value::Number(Number::from_f64(v).unwrap()) }
pub fn b(v: bool) -> Value { Value::Bool(v) }

pub fn track_t1_defaults() -> Vec<(&'static str, Value)> {
    vec![
        ("soc_levels", n(101)),
        ("action_grid", n(40)),
        ("asca_iters", n(25)),
        ("ternary_iters", n(25)),
        ("convergence_tol", f(1e-4)),
        ("k_clusters", n(80)),
        ("deflator_iters", n(200)),
        ("lp_refine_sweeps", n(0)),
        ("cg_iters", n(5)),
        ("use_lp", b(true)),
        ("use_sdp", b(true)),
        ("use_cg", b(true)),
        ("network_derating", f(1.00)),
        ("use_analytical_pricing", b(true)),
        ("use_pce_affine_recourse", b(false)),
        ("flow_margin", f(0.05)),
        ("use_cg_lp_combine", b(false)),
    ]
}

pub fn track_t2_defaults() -> Vec<(&'static str, Value)> {
    vec![
        ("soc_levels", n(201)),
        ("action_grid", n(40)),
        ("asca_iters", n(4)),
        ("ternary_iters", n(20)),
        ("deflator_iters", n(50)),
        ("network_derating", f(0.35)),
        ("max_admm_iters", n(10)),
        ("lp_total_pivots", n(15000)),
        ("dw_total_pivot_budget", n(8000)),
        ("lns_lp_pivots_total", n(6000)),
        ("use_lp", b(true)),
        ("use_dw", b(true)),
        ("use_lns", b(true)),
        ("use_kkt", b(true)),
        ("ct_step_eta", f(0.5)),
        ("dp_rho_jump", f(0.015)),
        ("ct_gdd_alpha", f(1.0)),
        ("lmp_threshold", f(0.65)),
        ("anticipate_lmp", b(true)),
        ("lmp_premium_scale", f(1.2)),
        ("use_primal_refine", b(true)),
        ("dw_mu_damping_alpha", f(0.6)),
        ("use_lmp_premiums_kkt", b(true)),
        ("use_ct_adaptive_per_line", b(true)),
        ("use_ptdf_constraint_tracking", b(true)),
    ]
}

pub fn track_t3_defaults() -> Vec<(&'static str, Value)> {
    vec![
        ("plan_sweeps", n(4)),
        ("plan_act_levels", n(17)),
        ("plan_soc_levels", n(97)),
        ("lahc_init_alpha_span", f(0.0)),
        ("seed_sel_mode", n(2)),
        ("use_lp_only", b(true)),
        ("dp_soc_levels", n(81)),
        ("dp_action_levels", n(9)),
        ("policy_action_levels", n(65)),
        ("proj_max_iters", n(80)),
        ("grad_outer_iters", n(80)),
        ("grad_ls_iters", n(6)),
        ("bisect_iters", n(30)),
        ("coord_polish_passes", n(0)),
        ("lookahead_horizon", n(24)),
        ("rh_stride", n(3)),
        ("pga_beta_end", f(0.6)),
        ("use_momentum", b(true)),
        ("use_bb_clamps", b(true)),
        ("soc_ref_lambda", f(0.05)),
        ("use_admm_solver", b(false)),
        ("use_cosine_beta", b(true)),
        ("soc_ref_dyn_stride", n(6)),
        ("joint_triplet_top_k", n(15)),
        ("use_rolling_horizon", b(true)),
        ("joint_triplet_budget", n(300)),
        ("use_joint_pair_polish", b(true)),
        ("use_joint_triplet_polish", b(false)),
        ("use_arb_seed", b(true)),
        ("arb_pct", n(75)),
        ("arb_inverse", b(true)),
        ("use_std_arb_third", b(true)),
        ("arb_pct_third", n(0)),
        ("use_da_arb_third", b(true)),
        ("use_rollout_additive", b(true)),
        ("rollout_window", n(12)),
        ("use_rollout_additive_2", b(true)),
        ("rollout_window_2", n(4)),
        ("use_rollout_additive_3", b(true)),
        ("rollout_window_3", n(2)),
        ("use_rollout_additive_4", b(true)),
        ("rollout_window_4", n(1)),
        ("use_basin_hop", b(false)),
        ("basin_hop_scale", f(0.05)),
        ("basin_hop_k", n(4)),
        ("pair_lahc_lh", n(5)),
    ]
}

pub fn track_t4_defaults() -> Vec<(&'static str, Value)> {
    vec![
        ("arb_diversity_inverse", b(true)),
        ("use_arb_diversity_pair", b(true)),
        ("use_arb_diversity_seed", b(true)),
        ("dp_soc_levels", n(81)),
        ("dp_action_levels", n(25)),
        ("policy_action_levels", n(113)),
        ("proj_max_iters", n(80)),
        ("grad_outer_iters", n(120)),
        ("grad_ls_iters", n(6)),
        ("bisect_iters", n(20)),
        ("coord_polish_passes", n(0)),
        ("lookahead_horizon", n(54)),
        ("cwv_lambda", f(0.1)),
        ("ct_step_eta", f(1.75)),
        ("use_dp_seed", b(false)),
        ("use_ptdf_ct", b(true)),
        ("ct_ref_kappa", f(0.0)),
        ("cwv_clusters", n(4)),
        ("use_momentum", b(true)),
        ("lmp_threshold", f(0.75)),
        ("lr_growth_cap", f(1.04)),
        ("use_bb_clamps", b(true)),
        ("use_zero_seed", b(false)),
        ("anticipate_lmp", b(true)),
        ("cwv_agg_levels", n(65)),
        ("use_cosine_beta", b(true)),
        ("use_composite_wv", b(true)),
        ("use_pwl_value_dp", b(false)),
        ("joint_pair_budget", n(1920)),
        ("lmp_premium_scale", f(1.0)),
        ("pwl_max_breakpoints", n(64)),
        ("congestion_grid_alpha", f(0.0)),
        ("use_joint_pair_polish", b(true)),
        ("use_gram_incremental_proj", b(true)),
        ("resync_period", n(16)),
        ("use_bb_step", b(false)),
        ("disagg_order_mode", n(0)),
        ("premium_shape_gamma", f(3.5)),
        ("ct_vq_v", f(100.0)),
        ("bb_decay_factor", f(0.85)),
        ("joint_triplet_top_k", n(30)),
        ("joint_triplet_budget", n(1200)),
    ]
}

pub fn track_t5_defaults() -> Vec<(&'static str, Value)> {
    vec![
        ("use_gram_incremental_proj", b(true)),
        ("dp_soc_levels", n(65)),
        ("dp_action_levels", n(9)),
        ("policy_action_levels", n(65)),
        ("proj_max_iters", n(80)),
        ("premium_shape_gamma", f(5.0)),
        ("grad_outer_iters", n(45)),
        ("grad_ls_iters", n(3)),
        ("bisect_iters", n(30)),
        ("coord_polish_passes", n(0)),
        ("lookahead_horizon", n(24)),
        ("num_seeds", n(3)),
        ("seed_order_mode", n(1)),
        ("extra_seed_mode", n(27)),
        ("pga_pool_claim_pct", n(0)),
        ("pga_dom_prune_pct", n(100)),
        ("cwv_lambda", f(0.7)),
        ("ct_step_eta", f(1.5)),
        ("use_ptdf_ct", b(true)),
        ("ct_gdd_alpha", f(0.0)),
        ("ct_ref_kappa", f(0.0)),
        ("use_momentum", b(true)),
        ("anticipate_lmp", b(true)),
        ("use_cosine_beta", b(false)),
        ("use_composite_wv", b(true)),
        ("joint_pair_budget", n(5500)),
        ("use_joint_pair_polish", b(false)),
        ("proj_relax", f(1.0)),
        ("use_basin_hop", b(false)),
        ("basin_hop_scale", f(0.05)),
        ("basin_hop_k", n(4)),
        ("pair_alpha_interval", b(true)),
        ("pair_alpha_max_passes", n(2)),
        ("joint_pair_early_exit_k", n(2000)),
        ("ct_vq_v", f(100.0)),
        ("use_dp_value_shift", b(true)),
        ("dp_value_curv_coef", f(0.65)),
        ("oco_full_rebuild", b(true)),
    ]
}
