// ============================================================================
// track_100k.rs -- wave13_parity
//
// The 100k track is now ONLY its constants.  Every line of the solver lives in
// `round_engine.rs`, which the four tracks share, so no optimisation can be
// present on one track and missing on another.  Generated by make_engine.py;
// every constant below was READ OUT of challengers/submission002_fastbok/
// track_100k.rs (the 20k) resp. the wave12_port merge (the three ports), so
// this file changes nothing about what the track computes.
// ============================================================================
use cudarc::{
    driver::{CudaModule, CudaStream},
    runtime::sys::cudaDeviceProp,
};
use serde_json::{Map, Value};
use std::sync::Arc;
use tig_challenges::hypergraph::*;

use super::round_engine::{solve_with, TrackKernels, TrackParams};

const PARAMS: TrackParams = TrackParams {
    name: "100k",
    block_size: 256,
    effort: [
        (500, 3, 20, 30, 32),
        (1000, 3, 25, 40, 32),
        (2000, 5, 50, 100, 64),
        (5000, 5, 50, 150, 64),
        (7000, 5, 60, 200, 0),
        (9000, 6, 70, 300, 0),
        (2000, 5, 50, 150, 64),
    ],
    tabu_tenure: 12,
    tabu_fail_tenure: 4,
    tabu_mark_base: 4096,
    tabu_fail_mark_len: 4096,
    extra_window: 61440,
    fused_mode: 2,
    dev_num_parts: 64,
    dev_warp_pin_threshold: 32,
    dev_giant_threshold: 256,
    dev_prefix_sampling: true,
    dev_all_parts_scan: false,
};

const KERNELS: TrackKernels = TrackKernels {
    hyperedge_clustering: "hyperedge_clustering_100k",
    compute_node_preferences: "compute_node_preferences_100k",
    execute_node_assignments: "execute_node_assignments_100k",
    precompute_edge_flags: "precompute_edge_flags_100k",
    compute_refinement_moves_optimized: "compute_refinement_moves_optimized_100k",
    fused_flags_moves: "fused_flags_moves_100k",
    fused_flags_moves_filter: "fused_flags_moves_filter_100k",
    fused_flags_moves_filter_flat: "fused_flags_moves_filter_flat_100k",
    fused_flags_moves_filter_flatw: "fused_flags_moves_filter_flatw_100k",
    balance_final: "balance_final_100k",
    compute_connectivity: "compute_connectivity_100k",
    reduce_connectivity_sum: "reduce_connectivity_sum_100k",
    compute_swap_gains_extended: "compute_swap_gains_extended_100k",
    choose_elite_per_hyperedge: "choose_elite_per_hyperedge_100k",
    assign_from_elite_votes: "assign_from_elite_votes_100k",
};

pub fn solve(
    challenge: &Challenge,
    save_solution: &dyn Fn(&Solution) -> anyhow::Result<()>,
    hyperparameters: &Option<Map<String, Value>>,
    module: Arc<CudaModule>,
    stream: Arc<CudaStream>,
    prop: &cudaDeviceProp,
) -> anyhow::Result<()> {
    solve_with(
        challenge,
        save_solution,
        hyperparameters,
        module,
        stream,
        prop,
        &PARAMS,
        &KERNELS,
    )
}
