name: Build Algorithm

on: 
  push:
    branches:
      - 'aarch64/satisfiability/*'
      - 'aarch64/vehicle_routing/*'
      - 'aarch64/knapsack/*'
      - 'aarch64/vector_search/*'

jobs:
  build_wasm:
    name: Compile Algorithm to Aarch64 .so
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v4
      - name: Set Env Vars
        run: |
          CHALLENGE=`echo $GITHUB_REF_NAME | rev | cut -d/ -f2 | rev`
          ALGORITHM=`echo $GITHUB_REF_NAME | rev | cut -d/ -f1 | rev`
          LIB_PATH=tig-algorithms/aarch64/${CHALLENGE}/${ALGORITHM}.so
          if [ -f $LIB_PATH ]; then
            echo "SKIP_JOB=true" >> $GITHUB_ENV
          else
            echo "SKIP_JOB=false" >> $GITHUB_ENV
          fi
          echo "CHALLENGE=$CHALLENGE" >> $GITHUB_ENV
          echo "ALGORITHM=$ALGORITHM" >> $GITHUB_ENV
      
      - name: Set up QEMU
        if: env.SKIP_JOB != 'true'
        uses: docker/setup-qemu-action@v3

      - name: Build Algorithm
        if: env.SKIP_JOB != 'true'
        uses: docker://ghcr.io/tig-foundation/tig-monorepo/tig-aarch64-dev:0.0.1
        with:
          entrypoint: '/bin/bash'
          args: '-c "rustup default nightly-2025-01-16 && ls && build.sh ${{ env.CHALLENGE }} ${{ env.ALGORITHM }}"'

      - name: Auto commit
        if: env.SKIP_JOB != 'true'
        id: auto_commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Compiled algorithm ${{ env.ALGORITHM }} into WASM

      - name: Update Commit Status (Success)
        if: env.SKIP_JOB != 'true' && success()
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: 'success'
          sha: ${{ steps.auto_commit.outputs.commit_hash }}

      - name: Update Commit Status (Failure)
        if: env.SKIP_JOB != 'true' && failure()
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: 'failure'
